import { createClient } from '@supabase/supabase-js'
import type { Product, BlogPost } from './mock-data'

const tenantId = process.env.NEXT_PUBLIC_TENANT_ID
const client = process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ? createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY, { auth: { persistSession: false } }) : null
export type DbCategory = { id:string; slug:string; name:string; description:string|null; icon:string|null; parent_id:string|null; sort_order:number|null; extra_data:Record<string,unknown>|null }
export async function dbCategories(): Promise<DbCategory[]|null> { if(!client||!tenantId)return null; const {data,error}=await client.from('product_categories').select('id,slug,name,description,icon,parent_id,sort_order,extra_data').eq('tenant_id',tenantId).eq('is_active',true).order('sort_order'); return error?null:data }
export async function dbProducts(): Promise<Product[]|null> { if(!client||!tenantId)return null; const {data,error}=await client.from('products').select('id,slug,name,description,category_slug,image_url,specs,extra_data').eq('tenant_id',tenantId).eq('is_active',true).order('sort_order'); if(error)return null; return data.map((row)=>{const extra=(row.extra_data||{}) as Record<string,any>;return{_id:row.id,title:row.name,slug:row.slug,category:row.category_slug,series:extra.series,shortDescription:row.description||'',description:row.description||'',specs:Array.isArray(row.specs)?row.specs:[],images:Array.isArray(extra.images)?extra.images.filter(Boolean):row.image_url?[row.image_url]:[],productVideo:extra.productVideo||null,seo:{title:`${row.name} | Baierde Electronic`,description:row.description||`${row.name} from Baierde Electronic`}} as Product}) }
export async function dbProduct(slug:string){const rows=await dbProducts();return rows===null?undefined:rows.find((row)=>row.slug===slug)||null}
export async function dbArticles(): Promise<BlogPost[]|null> { if(!client||!tenantId)return null; const {data,error}=await client.from('articles').select('id,slug,title,excerpt,content,published_at').eq('tenant_id',tenantId).eq('is_published',true).order('published_at',{ascending:false}); if(error)return null; return data.map((row)=>({_id:row.id,title:row.title,slug:row.slug,excerpt:row.excerpt||'',content:row.content||'',publishedAt:row.published_at,seo:{title:`${row.title} | Baierde Electronic`,description:row.excerpt||row.title}})) }
